@baseUrl = http://localhost:4000/api

# add new todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "userId": "f27c6096-d767-4fc8-90d8-48130a9fd29d",
  "description": "learn javascript",
  "severity": "medium",
  "status": "open"
}

###

## get todo list
GET {{baseUrl}}/todos

###

# get single todo
GET {{baseUrl}}/todos/77555a95-4712-4d21-b640-d31e8648771e

###

# add new todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "Learn React",
  "author": "Tony Nguyen",
  "description": "nihil aut laudantium",
  "severity": "low",
  "status": "new",
  "createdAt": 1617807944606,
  "updatedAt": 1617807944606
}


###

# update todo
PATCH {{baseUrl}}/todos/aH5vT_I
Content-Type: application/json

{
  "title": "Learn React",
  "author": "Tony Nguyen",
  "description": "nihil aut laudantium",
  "progress": 0,
  "severity": "low",
  "status": "new",
  "createdAt": 1617807944606,
  "updatedAt": 1617807944606
}

###

# delete todo
DELETE {{baseUrl}}/todos/gHIk2tx
Content-Type: application/json

###

# pagination
GET {{baseUrl}}/todos?_page=1&_limit=10