@baseUrl = http://localhost:4000/api

# get users
GET {{baseUrl}}/users

###

# add new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Leanne Graham 1",
  "email": "aincere@april.biz"
}

###

# update user
PATCH {{baseUrl}}/users/aH5vT_I
Content-Type: application/json

{
  "phone": "090734232",
  "address": "140/32 Dang Van Ngu"
}

###

# delete user
DELETE {{baseUrl}}/users/PZz1SBK
Content-Type: application/json

###

# pagination
GET {{baseUrl}}/users?_page=1&_limit=10