@baseUrl = http://localhost:4000/api

# get users
GET {{baseUrl}}/users

###
# get single user
GET {{baseUrl}}/users/f27c6096-d767-4fc8-90d8-48130a9fd29d

###

# add new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "avatar": "https://cdn.fakercloud.com/avatars/ManikRathee_128.jpg",
  "firstName": "Graham 1",
  "lastName": "Leanne",
  "email": "aincere@april.biz",
  "role": "operator",
  "location": [
    {
      "address": "243 Nguyen Thi Minh Khai",
      "district": "Phu Nhuan",
      "city": "TP.HCM"
    },
    {
      "address": "425 Nguyen Bieu",
      "district": "Phu Nhuan",
      "city": "TP.HCM"
    }
  ]
}

###

# update user
PATCH {{baseUrl}}/users/f27c6096-d767-4fc8-90d8-48130a9fd29d
Content-Type: application/json

{
  "avatar": "https://cdn.fakercloud.com/avatars/ManikRathee_128.jpg",
  "firstName": "Graham 1",
  "lastName": "Leanne",
  "email": "aincere@april.biz",
  "role": "operator",
  "location": [
    {
      "address": "243 Nguyen Thi Minh Khai",
      "district": "Phu Nhuan",
      "city": "TP.HCM"
    },
    {
      "address": "425 Nguyen Bieu",
      "district": "Phu Nhuan",
      "city": "TP.HCM"
    }
  ]
}


###

# delete user
DELETE {{baseUrl}}/users/PZz1SBK
Content-Type: application/json

###

# pagination
GET {{baseUrl}}/users?_page=1&_limit=10